<?xml version="1.0" ?>

<robot name="singlebot"
    xmlns:xacro="http://ros.org/wiki/xacro">


    <xacro:macro name="single" params="base_radius base_length hip_radius leg_length">

        <link name="base_link" />


        <link name="robot_base">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="3"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${base_radius}"/>
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${base_radius}"/>
                </geometry>
            </collision>
        </link>

        <link name="hip_back">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <mass value="0.3"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${hip_radius}" />
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <geometry>
                    <sphere radius="${hip_radius}" />
                </geometry>
            </collision>
        </link>

        <link name="leg_back">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <mass value="0.3"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <geometry>
                    <cylinder radius="0.05" length="${leg_length}"/>
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <geometry>
                    <cylinder radius="0.05" length="${leg_length}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${leg_length}"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${leg_length}"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </collision>
        </link>



        <link name="foot_back">
            <inertial>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <mass value="0.3"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <geometry>
                    <cylinder radius="0.05" length="${leg_length}"/>
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${0.5*leg_length}"/>
                <geometry>
                    <cylinder radius="0.05" length="${leg_length}"/>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0 0 0" xyz="0 0 ${leg_length}"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
                <material name="framemat0">
                    <color rgba="1 1 1 1" />
                </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${leg_length}"/>
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </collision>
        </link>

        <joint name="hip_back_joint" type="continuous">
            <parent link="base_link"/>
            <child link="hip_back"/>
            <origin xyz="0 0 ${-base_radius}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
        </joint>

        <joint name="leg_back_joint" type="continuous">
            <parent link="hip_back"/>
            <child link="leg_back"/>
            <origin xyz="0 0 0" rpy="0 3.1415 0" />
            <axis xyz="0 1 0" />
        </joint>


        <joint name="foot_back_joint" type="prismatic">
            <parent link="leg_back"/>
            <child link="foot_back"/>
            <origin xyz="0 0 ${1.0*leg_length}" rpy="0 0 0" />
            <axis xyz="0 0 1" />
            <limit lower="-0.1" upper="0.2" effort="20" velocity="1.0"/>
        </joint>

        <joint name="base_joint" type="fixed">
            <parent link="base_link"/>
            <child link="robot_base"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="1 0 0" />
        </joint>

    </xacro:macro>
</robot>