singlebot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

      # Position Controllers ---------------------------------------
  joint1_effort_controller:
    type: effort_controllers/JointEffortController
    joint: hip_back_joint
    pid: {p: 100.0, i: 0.00, d: 10.0}
  joint2_effort_controller:
    type: effort_controllers/JointEffortController
    joint: leg_back_joint
    pid: {p: 100.0, i: 0.00, d: 10.0}
  joint3_effort_controller:
    type: effort_controllers/JointEffortController
    joint: foot_back_joint
    pid: {p: 142.12230337568676, i: 0.00, d: 0.0}
