singlebot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

      # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: hip_back_joint
    pid: {p: 100.0, i: 0.00, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_back_joint
    pid: {p: 100.0, i: 0.00, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: foot_back_joint
    pid: {p: 100.0, i: 0.00, d: 10.0}
